# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97dc1c65a18359bd5da5b32515364b9c1ebd197fa6674d4da604b0c4b1893ca3e13d2c0b57ad3347bb324a73457ddee148cdfff81fe9ee808e3042362644eb14

test:
  secret_key_base: 13fb7d4655928b2cb37e81b0d24ab0de1ddb29043945636f5ca48d5698b1ffec9dffb1b14db3ee4b9f46da6b706c839b57845e3d222cad76e7a23ba8439d7579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
